=== oTruongChauMinhHuy/XMLProject/XMLProject/web/WEB-INF/Accounts.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           targetNamespace="http://www.fpt.edu.vn/project/account"
           xmlns:="http://www.fpt.edu.vn/project/account">
    <xs:element name="Accounts">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="account" type="Account"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="Account">
        <xs:sequence>
            <xs:element name="username" type="xs:string"/>
            <xs:element name="password" type="password"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
    </xs:complexType>
    <xs:simpleType name="password">
        <xs:restriction base="xs:string">
            
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== oTruongChauMinhHuy/XMLProject/XMLProject/web/WEB-INF/Accounts.xml
<?xml version="1.0" encoding="UTF-8"?>
<Accounts
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:='http://www.fpt.edu.vn/project/account'
    xsi:schemaLocation='http://www.fpt.edu.vn/project/account Accounts.xsd'>
    <account id="1">
        <username>HuyTCM</username>
        <password>1234</password>
    </account>
    <account id="2">
        <username>ThuyNTN</username>
        <password></password>
    </account>
    <account id="1">
        <username>HuyTCM</username>
        <password>1234</password>
    </account>
</Accounts>
